// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfUserExists(arg1:string):Promise<boolean>;

export function CreateUser(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoginUser(arg1:string,arg2:string):Promise<string>;
